Dev
DenisFilichev/dev-j120-laboratornaya-rabota-no5 pull request #2
Opened 2020-04-30 17:04 UTC by DenisFilichev

Добавлено сохранение товаров и заказов в файлы

2020-04-30 17:39 UTC, konivex requested changes
Чувствуется, что вы ещё не совсем распутались в том, что и как нужно сделать.

Исправьте общие замечания ниже и несколько мелких замечаний по коду и потом продолжим распутываться.

Общие замечания:
- переделать FileListReader и FileListWriter;
- классы по пакетам распределены бессистемно, перераспределите: сущности в одном пакете, списки сущностей в другом, классы чтения-записи в третьем.

2020-04-30 17:39 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/Application.java
>      public static void main(String[] args) {
Чтение и запись должны реализовываться в отдельном классе.

2020-04-30 17:39 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/Product.java
> +    public void setPrice(int price) {this.price = price;}
Проверка на значение меньше нуля?

2020-04-30 17:39 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/Product.java
>          this.price = price;
Проверка на значение меньше нуля?

2020-04-30 17:39 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/orders/Order.java
>      preparing, shipped, canceled
static final константы записываются в верхнем регистр. Константы enum'ов тоже static final, поэтому они должны записываться в верхнем регистре.

2020-05-01 14:41 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/Product.java
> +    public void setPrice(int price) {this.price = price;}
Операции с количествами, связанными с ними проверками и соответствующими сообщениями намеренно оставляю до появления окон, т.к. они будут тесно завязаны друг на друга.

2020-05-01 14:41 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/Product.java
>          this.price = price;
Операции с количествами, связанными с ними проверками и соответствующими сообщениями намеренно оставляю до появления окон, т.к. они будут тесно завязаны друг на друга.

2020-05-02 07:44 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/Product.java
>          this.price = price;
Цена товара вводится пользователями вручную, как при создании нового товара, так и при его корректировке. Проверку вводимых значений целесообразно реализовать когда будет сделана оконная часть программы. Реализация будет такая:
- пользователь вводит значение;
- программа проверяет значение на соответствие требованиям;
- значение передается в качестве параметров для создания объекта.

2020-05-02 07:44 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/Product.java
> +    public void setPrice(int price) {this.price = price;}
Цена товара вводится пользователями вручную, как при создании нового товара, так и при его корректировке. Проверку вводимых значений целесообразно реализовать когда будет сделана оконная часть программы. Реализация будет такая:

пользователь вводит значение;
программа проверяет значение на соответствие требованиям;
значение передается в качестве параметров для создания объекта.

2020-05-02 07:45 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/Application.java
>      public static void main(String[] args) {
Исправлено

2020-05-02 07:46 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/orders/Order.java
>      preparing, shipped, canceled
Исправлено

2020-05-02 07:46 UTC, closed without merging

2020-05-02 07:47 UTC, DenisFilichev commented
Часть замечаний исправлено, часть оставлена до реализации оконного режима программы.

2020-05-06 19:22 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/Product.java
>          this.price = price;
Такой подход не защищает вас от случаев, когда этот атрибут будет заполняться не из пользовательского интерфейса, а откуда-либо ещё (например, загрузка XML-файла из сети) — в этом случае можно получить объект `Product` в некорректном состоянии.