Dev
DenisFilichev/dev-j120-laboratornaya-rabota-no5 pull request #4
Opened 2020-05-22 17:00 UTC by DenisFilichev

2020-05-22 18:03 UTC, konivex requested changes
Графический интерфейс тоже можно смотреть?

2020-05-22 18:03 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/models/Order.java
> +            Product prodOrder = new Product(prod.getID(), prod.getName(), prod.getColor());
Зачем создавать копию продукта, если можно запомнить ссылку на оригинал?

2020-05-22 18:03 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/controlers/FileListOrders.java
> +public class FileListOrders {
Исправьте этот класс и FileListProducts так, чтобы их методы были instance, а не static.

2020-05-22 18:03 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/Application.java
> +
Если что-то не получилось прочитать, то надо вывести human-readable сообщение об этом и завершить работу..

2020-05-22 18:03 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/Application.java
> +        } catch (IOException e) {}
Пользователя нужно проинформировать и наличии проблем с сохранением результатов его работы.

2020-05-22 18:03 UTC, konivex commented on src/ru/avalon/java/dev/j12/labs/controlers/SearchByID.java
> +        for (Object obj : list){
Вместо `Object obj` можно написать `T obj`, тогда вместо `if (((T)obj).getID()==ID)` можно будет писать `if (obj.getID()==ID)`.

2020-05-23 21:46 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/models/Order.java
> +            Product prodOrder = new Product(prod.getID(), prod.getName(), prod.getColor());
Я целенаправлено делаю копию товара, так сказать слепок приобретаемого товара и последующие возможные изменения корневого товара ни как не отразятся на истории сделанных ранее заказов. Т.е., например, со временем поменяется цена товара или его описание и это ни как не отразится на уже проданных экземплярах данного товара.

2020-05-23 21:52 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/controlers/FileListOrders.java
> +public class FileListOrders {
Сделано

2020-05-23 22:17 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/Application.java
> +
Сделано

2020-05-23 22:28 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/Application.java
> +        } catch (IOException e) {}
Сделано

2020-05-23 22:32 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j12/labs/controlers/SearchByID.java
> +        for (Object obj : list){
Сделано

2020-05-24 12:43 UTC, konivex approved these changes
Зачтено.

2020-05-24 20:45 UTC, merged